# Generated by Django 5.2.7 on 2026-01-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthio', '0002_alter_diary_content_alter_dish_how_to_make_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='cv',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='expert',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
