# Generated by Django 5.2.7 on 2026-01-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthio', '0004_alter_customer_user_alter_expert_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='role',
            field=models.IntegerField(choices=[(1, 'Huấn luyện viên'), (2, 'Chuyên gia dinh dưỡng')], default=1),
        ),
    ]
