# Generated by Django 5.2.7 on 2026-01-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthio', '0005_alter_expert_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='expert',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
