# Generated by Django 5.2.7 on 2026-01-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthio', '0006_alter_expert_cv_alter_expert_description'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='practice',
            name='unique_practice_per_day_per_schedule',
        ),
        migrations.AddConstraint(
            model_name='practice',
            constraint=models.UniqueConstraint(fields=('schedule', 'day_in_week'), name='unique_practice_per_schedule'),
        ),
    ]
