# Generated by Django 5.2.7 on 2026-01-05 13:56

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthio', '0007_remove_practice_unique_practice_per_day_per_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='self_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='practicedetail',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
