# Generated by Django 5.2.7 on 2026-01-06 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthio', '0008_customer_self_mode_dish_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealdetail',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_details', to='healthio.dish'),
        ),
        migrations.AlterField(
            model_name='mealdetail',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_details', to='healthio.meal'),
        ),
    ]
