# Generated by Django 5.2.7 on 2026-01-07 13:34

import ckeditor.fields
import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthio', '0009_alter_mealdetail_dish_alter_mealdetail_meal'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Diary',
            new_name='HealthDiary',
        ),
        migrations.RemoveField(
            model_name='mealdetail',
            name='dish',
        ),
        migrations.RenameField(
            model_name='practicedetail',
            old_name='is_completed',
            new_name='is_complete',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='expert',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='self_mode',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_type',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='is_custom',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='number_of_times',
        ),
        migrations.RemoveField(
            model_name='practicedetail',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='practicedetail',
            name='times',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='made_by_ai',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='schedule_type',
        ),
        migrations.AddField(
            model_name='conversation',
            name='contract',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='healthio.contract'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='birth_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='MET',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='feedback',
            name='star',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealdetail',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealdetail',
            name='how_to_make',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealdetail',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mealdetail',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='healthio.customer'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='healthio.expert'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='healthio.contract'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='practicedetail',
            name='practice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_details', to='healthio.practice'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Nam'), (2, 'Nữ')], default=1),
        ),
        migrations.CreateModel(
            name='DishSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('calories', models.IntegerField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('how_to_make', ckeditor.fields.RichTextField()),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_samples', to='healthio.expert')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_samples', to='healthio.exercise')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_samples', to='healthio.expert')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='health_goal',
            field=models.ManyToManyField(to='healthio.healthgoal'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='health_goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='healthio.healthgoal'),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='healthio.contract')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
    ]
