# Generated by Django 5.2.7 on 2026-01-07 15:00

import ckeditor.fields
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthio', '0010_healthgoal_rename_diary_healthdiary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mealdetail',
            name='how_to_make',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
