# Generated by Django 5.2.7 on 2026-01-07 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthio', '0011_exercise_image_alter_mealdetail_how_to_make'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealdetail',
            name='image',
        ),
    ]
