# Generated by Django 5.2.7 on 2026-01-07 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthio', '0012_remove_mealdetail_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='end_date',
        ),
    ]
