# Generated by Django 5.2.7 on 2026-01-08 05:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthio', '0014_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='height',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='weight',
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='record_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='healthio.customer'),
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='drink_amount',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='heart_rate',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='steps',
        ),
    ]
