# Generated by Django 5.2.7 on 2026-01-08 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthio', '0015_remove_customer_height_remove_customer_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drink_amount', models.IntegerField(default=0)),
                ('steps', models.IntegerField(default=0)),
                ('heart_rate', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='drink_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='healthrecord',
            constraint=models.UniqueConstraint(fields=('customer', 'record_date'), name='unique_daily_record'),
        ),
        migrations.AddField(
            model_name='record',
            name='health_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthio.healthrecord'),
        ),
    ]
