# Generated by Django 5.2.7 on 2026-01-08 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthio', '0016_record_healthrecord_drink_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealdetail',
            name='icon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mealdetail',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mealdetail',
            name='unit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_status',
            field=models.IntegerField(choices=[(1, 'Đang chờ xử lí'), (2, 'Đã được duyệt'), (3, 'Bị từ chối')], default=1),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='healthio.contract'),
        ),
        migrations.AlterField(
            model_name='practicedetail',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_details', to='healthio.exercise'),
        ),
        migrations.AlterField(
            model_name='request',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthio.contract'),
        ),
    ]
