# Generated by Django 5.2.7 on 2026-01-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthio', '0017_mealdetail_icon_mealdetail_quantity_mealdetail_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
