# Generated by Django 5.2.7 on 2026-01-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthio', '0018_alter_contract_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
