# Generated by Django 5.2.7 on 2026-01-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthio', '0019_alter_reminder_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='avg_star',
            field=models.FloatField(default=0),
        ),
    ]
