# Generated by Django 5.2.7 on 2026-01-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthio', '0020_expert_avg_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealdetail',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
