# Generated by Django 5.2.7 on 2026-01-09 06:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthio', '0021_alter_mealdetail_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealdetail',
            name='how_to_make',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mealdetail',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
