# Generated by Django 5.2.7 on 2026-01-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthio', '0022_alter_mealdetail_how_to_make_alter_mealdetail_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealdetail',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
