# Generated by Django 5.2.7 on 2026-01-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthio', '0023_mealdetail_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicedetail',
            name='actual_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='practicedetail',
            name='calories_target',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='practice',
            name='total_calories',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='practicedetail',
            name='calories_burned',
            field=models.FloatField(default=0),
        ),
    ]
